language: objective-c
osx_image: xcode8.3
rvm:
- 2.3
install:
  - make init
script:
  - make test
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f build/Reports/cobertura.xml -X coveragepy -X gcov -X xcode
