name: Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: make init
    - name: Run tests
      run: make test
